from __future__ import annotations

from typing import Any, Protocol

from .models import PendingConfirmation, WishlistItem


class ShoppingRepository(Protocol):
    """Persistence port; Supabase can replace JsonRepository without changing agents."""

    def save_item(self, item: WishlistItem) -> None: ...

    def get_item(self, item_id: str) -> WishlistItem | None: ...

    def find_item_by_url(self, url: str) -> WishlistItem | None: ...

    def list_items(self) -> list[WishlistItem]: ...

    def save_pending(self, pending: PendingConfirmation) -> None: ...

    def get_pending(self, pending_id: str) -> PendingConfirmation | None: ...

    def delete_pending(self, pending_id: str) -> None: ...

    def append_observation(self, record: dict[str, Any]) -> None: ...

    def append_alert(self, record: dict[str, Any]) -> None: ...

    def append_audit(self, record: dict[str, Any]) -> None: ...
